name: Generate Docs

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn

    - name: Generate Documentation
      run: yarn build:docs

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/* -f
        git commit -m "Update docs @ $(date '+%Y.%m.%d')" -a || echo "No changes to commit"
        git push
