name: Generate Docs and Deploy

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2) setup node
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3) install
      - name: Install dependencies
        run: yarn

      # 4) build docs
      - name: Generate Documentation
        run: yarn build:docs

      # 5) setup pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 6) upload docs
      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      # 7) deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
